### ISSUE TITLE
Silent Name Clashing

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#13]
**Describe the bug**
Defining an input with the same name but different type of an input inferred from using `csl_spl_assoc_token.create` does not throw, but silently overrides the user defined param.

**To Reproduce**
```
- name: name_clashing_test
    uses:
      - csl_spl_assoc_token.create
   inputs:
      - name: wallet -----> Silently overrided
        type: u8
```

stub:
```
pub fn create_nft_without_optional_fields(
	program_id: &Pubkey,
	for_create: &[AccountInfo],
	funding: &AccountInfo,
	assoc_token_account: &AccountPDA<csl_spl_assoc_token::src::state::Account>,
	wallet: &AccountInfo, ----------------------------------------------------------------> **Silently overrided**
	mint: &Account<csl_spl_assoc_token::src::state::Mint>,
) -> ProgramResult {
    // Implement your business logic here...
	csl_spl_assoc_token::src::cpi::create(
		for_create,
	)?;

    Ok(())
}
```

**Expected behavior**
To throw an error and feedback at validations stage

**Código CLI version:**
 - Version v0.8
