### ISSUE TITLE
Misleading Generation Error Trying to Init An AccountInfo

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#14]
**Describe the bug**
Not a bug but bad user xp.
If a CIDL has an input of type `sol:account_info` with the `init` attr, it panics with "EOF" as error.

**To Reproduce**
```
methods:
  - name: gives_error
    inputs:
      - name: my_acc_info
        type: sol:account_info
        solana:
          attributes: [ init ]

```
**Expected behavior**
To deny generation with a user friendly msg.

**Screenshots**
![image](https://github.com/Codigo-io/issues/assets/63513231/2e20e046-6e89-4f65-b027-897befe9d8d8)

**Código CLI version:**
 - Version v0.8
