### ISSUE TITLE
[Anchor] Inferred Dynamic Seeds Appears As Stub Param

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#17]
**Describe the bug**
Unrequested inferred parametric dynamic seeds appears as stub params.

**To Reproduce**
CIDL:
```
- name: create_user_record
    solana:
      signers:
        - name: fee_payer
  inputs:
      - name: user_record
        type: Record
        solana:
          attributes: [ init, mut ]
          seeds:
            signer: fee_payer
      - name: user_name
        type: string
```

Anchor's stub
```
pub fn create_user_record(
    ctx: Context<CreateUserRecord>,
   user_name:String, 
   user_record_seed_index:u8 --------> Shouldn't appear
) -> Result<()> {
}
```

**Expected behavior**
To not include unmapped inferred seeds as stub param

**Código CLI version:**
 - Version v0.8
