### ISSUE TITLE
Throw an error if `signers` kw appear without solana

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#30]
**Is your enhancement request related to a problem? Please describe.**
If the `solana` kw is absent before `signers`, no error is thrown and the signers list is just ignored.

**Describe the solution you'd like**
To throw an error if a block that should have been under a bigger block is not well crafted (we can think of this particular case as an instance of a  general problem)

Example, don't silently ignore the signers list and generate:
```
- name: create_global_state
  signers: ----------> This should have been used under `solana`
    - name: admin
  inputs:
    - name: bps
      type: u16
```

I'm thinking maybe in checking the presence of secondary keywords nevertheless their primary kw is not present to give the validator enough info.
