### ISSUE TITLE
Anchor || Method name MUST use camelCase in the client

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#31]
**Describe the bug**
To define a method name, the CIDL guidelines indicates to use snake_case.
Then, when generating for Anchor, the snake_cased method turns uncallable from the client, because Anchor mangles the name from snake_case to CamelCase.

**To Reproduce**
CIDL:
```
- name: create_global_state
  signers:
    - name: admin
  inputs:
    - name: bps
      type: u16
    - name: global_state
      type: GlobalState
      solana:
        attributes: [ init ]
```

Generated client code:
![image](https://github.com/Codigo-io/issues/assets/63513231/dd4f2ebd-4b1d-46d7-a5c5-205609d8ac2d)

Error:
`TypeError: exports.program.methods.create_global_state is not a function`

**Expected behavior**
To mangle snaked_case method names to CamelCase on the client side at every call of program.methods.<methodName>

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version 0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
