### ISSUE TITLE
Código's client method names exposed with UpperCamelCase

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#34]
**Is your enhancement request related to a problem? Please describe.**
Methods on the generates client library are exposed with UpperCamelCase.
The convention is to use camelCase.

CIDL
```
- name: change_bps
    inputs:
      - name: new_bps
        type: u16
      - name: global_state
        type: GlobalState
        solana:
          attributes: [ mut ]
```

Generated Client
![image](https://github.com/Codigo-io/issues/assets/63513231/bc191759-b304-42a2-b7f4-e1cbfd46cbfc)

The convention is to name it `changeBps`... rather than `ChangeBps`...
