### ISSUE TITLE
[native] Using account compression append ix generate code that doesn't build

### ISSUE THREAD

**Issue by JazielGuerrero** [Codigo-io/issues#35]
**Describe the bug**
Using the `csl_spl_account_compression.append` instruction generates code that doesn't build. The call to the CPI expects a variable named `leaf` that doesn't exist. 

**To Reproduce**
1. Copy and paste your CIDL:
```yaml
types:
  Article:
    solana:
      compress: true
    fields:
      - name: name 
        type: string
        solana:
          attributes: [ cap:96 ]
      - name: description
        type: string
        solana:
          attributes: [ cap:255 ]
      - name: thumbnail
        type: string
        solana:
          attributes: [ cap:2048 ]
      - name: mint
        type: sol:pubkey
      - name: owner
        type: sol:pubkey
      - name: current_warehouse
        type: rs:option<sol:pubkey>    
methods:
  - name: create_article
    solana:
      signers: 
        - name: fee_payer
        - name: delegate
    uses:
      - csl_spl_token.initialize_mint2
      - csl_spl_assoc_token.create
      - csl_spl_token.mint_to
      - csl_spl_token.set_authority
      - csl_spl_account_compression.append
    inputs:
      - name: warehouse
        type: Warehouse
      - name: mint
        type: csl_spl_token.Mint
        solana:
          attributes: [ init ]
      - name: delegate
        type: sol:account_info
      - name: name
        type: string
      - name: description
        type: string
      - name: thumbnail
        type: string
```
2. If applicable, copy and paste your business logic
```rust
pub fn create_article(
	program_id: &Pubkey,
	for_initialize_mint_2: &[AccountInfo],
	for_create: &[AccountInfo],
	for_mint_to: &[AccountInfo],
	for_set_authority: &[AccountInfo],
	for_append: &[AccountInfo],
	warehouse: &AccountPDA<Warehouse>,
	mint: &Account<spl_token::state::Mint>,
	delegate: &AccountInfo,
	funding: &AccountInfo,
	assoc_token_account: &AccountInfo,
	wallet: &AccountInfo,
	owner: &AccountInfo,
	merkle_tree: &AccountInfo,
	authority: &AccountInfo,
	noop: &AccountInfo,
	account_compression: &AccountInfo,
	name: String,
	description: String,
	thumbnail: String,
) -> ProgramResult {
    // Implement your business logic here...

	csl_spl_token::src::cpi::initialize_mint_2(for_initialize_mint_2, 0, *wallet.key, None)?;
	csl_spl_assoc_token::src::cpi::create(for_create)?;
	csl_spl_token::src::cpi::mint_to(for_mint_to, 1)?;
	csl_spl_token::src::cpi::set_authority(for_set_authority, 0, None)?;

	csl_spl_account_compression::src::cpi::append(
		for_append,
		leaf.to_vec(), // <-- not found in this scope
	)?;

    Ok(())
}
```
3. If applicable, copy and paste in what context you are calling the client library functions
N/A

**Expected behavior**
To throw a validation error if I doing something wrong or generate the corresponding leaf variable.

**Screenshots**
N/A

**Platform version:**
 - CLI Version v0.1.0
 - GenService Version v0.1.0

**Extension (mark with an X the extension):**
 - Solana Native [X]
 - Solana Anchor [ ]
   
**Additional context**
The issue is that I didn't specify the article account to my method:
```yaml
  - name: create_article
    solana:
      signers: 
        - name: fee_payer
        - name: delegate
    uses:
      - csl_spl_token.initialize_mint2
      - csl_spl_assoc_token.create
      - csl_spl_token.mint_to
      - csl_spl_token.set_authority
      - csl_spl_account_compression.append
    inputs:
      - name: warehouse
        type: Warehouse
      - name: mint
        type: csl_spl_token.Mint
        solana:
          attributes: [ init ]
      - name: article # <-- Adding this fix the issue
        type: Article
      - name: delegate
        type: sol:account_info
      - name: name
        type: string
      - name: description
        type: string
      - name: thumbnail
        type: string
```
