### ISSUE TITLE
[native] Using account compression generates code that doesn't allow program to build

### ISSUE THREAD

**Issue by JazielGuerrero** [Codigo-io/issues#36]
**Describe the bug**
Using state compression generates code that doesn't build. cannot find function `save_application_data` in module `csl_spl_account_compression::src::cpi`

**To Reproduce**
1. Copy and paste your CIDL:
```yaml
  Article:
    solana:
      compress: true
    fields:
      - name: name 
        type: string
        solana:
          attributes: [ cap:96 ]
      - name: description
        type: string
        solana:
          attributes: [ cap:255 ]
      - name: thumbnail
        type: string
        solana:
          attributes: [ cap:2048 ]
      - name: mint
        type: sol:pubkey
      - name: owner
        type: sol:pubkey
      - name: current_warehouse
        type: rs:option<sol:pubkey>      
methods:
  - name: create_article
    solana:
      signers: 
        - name: fee_payer
        - name: delegate
    uses:
      - csl_spl_token.initialize_mint2
      - csl_spl_assoc_token.create
      - csl_spl_token.mint_to
      - csl_spl_token.set_authority
      - csl_spl_account_compression.append
    inputs:
      - name: warehouse
        type: Warehouse
      - name: mint
        type: csl_spl_token.Mint
        solana:
          attributes: [ init ]
      - name: article
        type: Article
      - name: delegate
        type: sol:account_info
      - name: name
        type: string
      - name: description
        type: string
      - name: thumbnail
        type: string

```        
2. If applicable, copy and paste your business logic
N/A
3. If applicable, copy and paste in what context you are calling the client library functions
N/A
4. If applicable, copy and paste the generated code
```rust
impl Article {
	pub const LEN: usize = 2508; 
	pub const DISCRIMINATOR: u32 = 1;

	pub fn compress(&self, merkle_tree: &Pubkey, noop: &AccountInfo) -> [u8; 32] {
		let mut application_data_buffer: Vec<u8> = Vec::new();
		self.serialize(&mut application_data_buffer).unwrap();
	
		let mut hasher = Sha256::new();
		let hash_bytes: [u8; Article::LEN] = application_data_buffer.clone().try_into().unwrap();
		hasher.update(hash_bytes);
		let leaf: [u8; 32] = hasher.finalize().as_slice().try_into().unwrap();
	
	        /// The following function in state.rs throws: cannot find function `save_application_data` 
                /// in module `csl_spl_account_compression::src::cpi`
		csl_spl_account_compression::src::cpi::save_application_data(
			&[noop.clone()],
			Article::DISCRIMINATOR,
			leaf.to_vec(),
			*merkle_tree,
			application_data_buffer,
		);

		return leaf;
	}
}
```

**Expected behavior**
Throw a validation error if I'm doing something wrong or generate the code correctly. 

**Screenshots**
N/A

**Platform version:**
 - CLI Version v0.1.0
 - GenService Version v0.1.0

**Extension (mark with an X the extension):**
 - Solana Native [X]
 - Solana Anchor [ ]
   
**Additional context**
Adding the uses `csl_spl_account_compression.save_application_data` to the `create_article` method fixed the issue.
