### ISSUE TITLE
[native] Initializing a merkle tree using `init_if_needed` crashes the generator with `EOF`

### ISSUE THREAD

**Issue by JazielGuerrero** [Codigo-io/issues#38]
**Describe the bug**
When defining a method that will initialize a `sol:merkle_tree` using `init_if_needed` causes the generator to crash with the error `EOF`.

**To Reproduce**
1. Copy and paste your CIDL:
```yaml
  - name: initialize_merkle_tree
    uses:
      - csl_spl_account_compression.init_empty_merkle_tree
    inputs:
      - name: merkle_tree
        type: sol:merkle_tree
        solana:
          attributes: [init_if_needed, cap:50]
```
2. If applicable, copy and paste your business logic
N/A
3. If applicable, copy and paste in what context you are calling the client library functions
N/A

**Expected behavior**
Be able to define a method that will initialize a merkle tree using the `init_if_needed` attribute.

**Screenshots**
N/A

**Platform version:**
 - CLI Version v0.1.0
 - GenService Version v0.1.0

**Extension (mark with an X the extension):**
 - Solana Native [X]
 - Solana Anchor [ ]
   
**Additional context**
