### ISSUE TITLE
[native] Cannot initialize a merkle tree when additional inputs are defined, generator crashes with `EOF`

### ISSUE THREAD

**Issue by JazielGuerrero** [Codigo-io/issues#39]
**Describe the bug**
When using the method `csl_spl_account_compression.init_empty_merkle_tree` with additional inputs besides the `sol:merkle_tree` causes the generator to crash with `EOF`

**To Reproduce**
1. Copy and paste your CIDL:
```yaml
methods:
  - name: create_article_merkle_tree
    uses:
      - csl_spl_account_compression.init_empty_merkle_tree
    inputs:
      - name: merkle_tree
        type: sol:merkle_tree
        solana:
          attributes: [init, cap:100000000]
      - name: input
        type: u8
```
2. If applicable, copy and paste your business logic
N/A
3. If applicable, copy and paste in what context you are calling the client library functions
N/A

**Expected behavior**
Be able to initialize a merkle tree regardless of how many inputs I have defined.

**Screenshots**
N/A

**Platform version:**
 - CLI Version v0.1.0
 - GenService Version v0.1.0

**Extension (mark with an X the extension):**
 - Solana Native [X]
 - Solana Anchor [ ]
   
**Additional context**
N/A
