### ISSUE TITLE
[native] unused `for_save_application_data` parameter generated when using `csl_spl_account_compression.save_application_data`

### ISSUE THREAD

**Issue by JazielGuerrero** [Codigo-io/issues#41]
**Describe the bug**
When using the method `csl_spl_account_compression.save_application_data`, in my stub it generates a parameter for the given CPI `for_save_application_data`. But this parameter is never used nor the call to `csl_spl_account_compression.save_application_data` generates in the stub (it gets generated in the state.rs).

**To Reproduce**
1. Copy and paste your CIDL:
```yaml
  - name: create_article
    solana:
      signers: 
        - name: fee_payer
        - name: delegate
    uses:
      - csl_spl_token.initialize_mint2
      - csl_spl_assoc_token.create
      - csl_spl_token.mint_to
      - csl_spl_token.set_authority
      - csl_spl_account_compression.append
      - csl_spl_account_compression.save_application_data
    inputs:
      - name: warehouse
        type: Warehouse
      - name: mint
        type: csl_spl_token.Mint
        solana:
          attributes: [ init ]
      - name: article
        type: Article
      - name: delegate
        type: sol:account_info
      - name: name
        type: string
      - name: description
        type: string
      - name: thumbnail
        type: string
```
2. If applicable, copy and paste your business logic
```rust
pub fn create_article(
    program_id: &Pubkey,
    for_initialize_mint_2: &[AccountInfo],
    for_create: &[AccountInfo],
    for_mint_to: &[AccountInfo],
    for_set_authority: &[AccountInfo],
    for_append: &[AccountInfo],
    for_save_application_data: &[AccountInfo],
    warehouse: &AccountPDA<Warehouse>,
    mint: &Account<spl_token::state::Mint>,
    delegate: &AccountInfo,
    funding: &AccountInfo,
    assoc_token_account: &AccountInfo,
    wallet: &AccountInfo,
    owner: &AccountInfo,
    merkle_tree: &AccountInfo,
    authority: &AccountInfo,
    noop: &AccountInfo,
    account_compression: &AccountInfo,
    name: String,
    description: String,
    thumbnail: String,
) -> ProgramResult {
    if !warehouse.data.delegates.contains(delegate.key) {
        return Err(InventoryError::NotExpectedAddress.into());
    }

    let mut article = Article::default();
    article.name = name;
    article.description = description;
    article.thumbnail = thumbnail;
    article.mint = *mint.info.key;
    article.current_warehouse = Some(*warehouse.info.key);
    article.owner = *assoc_token_account.key;

    let leaf = article.compress(merkle_tree.key, noop);

    csl_spl_token::src::cpi::initialize_mint_2(for_initialize_mint_2, 0, *wallet.key, None)?;
    csl_spl_assoc_token::src::cpi::create(for_create)?;
    csl_spl_token::src::cpi::mint_to(for_mint_to, 1)?;
    csl_spl_token::src::cpi::set_authority(for_set_authority, 0, None)?;
    csl_spl_account_compression::src::cpi::append(for_append, leaf.to_vec())?;

    Ok(())
}
```
3. If applicable, copy and paste in what context you are calling the client library functions

**Expected behavior**
To not generate the `for_save_application_data` parameter

**Screenshots**
N/A

**Platform version:**
 - CLI Version v0.1.0
 - GenService Version v0.1.0

**Extension (mark with an X the extension):**
 - Solana Native [X]
 - Solana Anchor [ ]
   
**Additional context**
N/A
