### ISSUE TITLE
Anchor || Wrong `derive<Struct>` function name at client

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#42]
**Describe the bug**
When a PDA is derived using a dynamic seed, the generated `derive `fn is called internally both in the Ix Builder and the SendAndConfirm functions.
While the generated signature fn name is `derive<StructName>`, when called it is wrongly called as `derive<ProgramName><StructName>`

**To Reproduce**
CIDL:
```
StakeAccount:
    solana:
      seeds:
        - name: "stake"
        - name: user
          type: sol:pubkey
```

Generated client code:
```
export const deriveStakeAccount = (
	seeds : StakeAccountSeeds) : anchor.web3.PublicKey => {
	const [pubkey, bump] = anchor.web3.PublicKey.findProgramAddressSync(
		[
			Buffer.from("stake"),
			toPubkey(seeds.user).toBuffer()
		],
		PROGRAM_PUBKEY
	)
	return pubkey
};
```

fn call:
![image](https://github.com/Codigo-io/issues/assets/63513231/dd67c51c-d2fe-4453-b4a8-cf8c41266125)

**Platform version:**
 - GenService Version 0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
