### ISSUE TITLE
Anchor || A PDA account with no attributes does not generate PDA checks

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#43]
**Describe the bug**
If a PDA input is used without any attribute, the generated code does not include the PDA checks.

It is unclear if this behavior is happening also with native.

**To Reproduce**
CIDL:
```
...
types:
  GlobalState:
    solana:
      seeds:
        - name: "global"
    fields:
      - name: admin
        type: sol:pubkey
      - name: bps
        type: u16
...
methods:
  - name: create_global_state
    inputs:
      - name: bps
        type: u16
      - name: global_state
        type: GlobalState
        solana:
          attributes: [ init ]
  - name: change_admin
    inputs:
      - name: new_admin
        type: sol:pubkey
      - name: global_state
        type: GlobalState
        solana:
          attributes: [ mut ]
  - name: stake
    solana:
      signers:
        - name: fee_payer
    inputs:
      - name: amount
        type: u64
      - name: global_state
        type: GlobalState ----------------> Notice that there is no attributes
      - name: stake_account
 ...

```

generated lib.rs:
```
...
 #[derive(Accounts)]
    #[instruction(bps:u16)]
    pub struct CreateGlobalState<'info> {
        /// CHECK: fee_payer requires an account info
        #[account(mut, signer)]
        pub fee_payer: AccountInfo<'info>,
        #[account(init, space=42, payer=fee_payer, seeds = [b"global"], bump)]
        pub global_state: Account<'info, GlobalState>,

        /// CHECK: system_program requires an account info
        pub system_program: AccountInfo<'info>,
    }
...
pub struct ChangeAdmin<'info> {
        /// CHECK: fee_payer requires an account info
        #[account(mut, signer)]
        pub fee_payer: AccountInfo<'info>,
        #[account(mut, seeds = [b"global"], bump)]
        pub global_state: Account<'info, GlobalState>,
    }
...
 pub struct Stake<'info> {
        /// CHECK: fee_payer requires an account info
        #[account(mut, signer)]
        pub fee_payer: AccountInfo<'info>,

        pub global_state: Account<'info, GlobalState>,------> Notice the lack of PDA checks

        #[account(init_if_needed, space=42, payer=fee_payer, seeds = [b"stake", fee_payer.key().as_ref()], bump)]
        pub stake_account: Account<'info, StakeAccount>,
...


**Expected behavior**
To always check a PDA address, no matter its attributes field.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Platform version:**
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ] Unknown yet
 - Solana Anchor [x]
