### ISSUE TITLE
Wrong mutability for rent-receiver

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#49]
**Describe the bug**
If specified as rent-receiver, an account is not marked as mutable.
In this [branch ](https://github.com/Codigo-io/generators/tree/test/anchor-counter)I placed a test with a script that shows the issue. To run, from root: `./scripts/anchor_counter.sh`

**To Reproduce**
CIDL
```
- name: close_counter
    solana:
      signers:
        - name: fee_payer
        - name: rent_receiver
    inputs:
      - name: counter
        type: Counter
        solana:
          attributes: [ close ]
          rent-receiver: rent_receiver
          seeds:
            user: rent_receiver
```

generated lib.rs
```
#[derive(Accounts)]
    pub struct CloseCounter<'info> {
        /// CHECK: fee_payer requires an account info
        #[account(mut, signer)]
        pub fee_payer: AccountInfo<'info>,

        /// CHECK: rent_receiver requires an account info
        #[account(signer)]--------------------------------------------> Notice that is not mutable when it should have
        pub rent_receiver: AccountInfo<'info>,
        #[account(mut, close=rent_receiver, seeds = [rent_receiver.key().as_ref()], bump)]
        pub counter: Account<'info, Counter>,
    }
```

**Expected behavior**
To mark as mutable rent-receiver accounts.

**Screenshots**

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
