### ISSUE TITLE
Cpi lib name generated in some parts with ref name

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#54]
**Describe the bug**
The ref name is being used to generate cpi related code (not always, but in some places).
This produces unbuildeable code if the ref name differs from the imported cidl program name.

**To Reproduce**
```
cidl: "0.8"
imports:
  - ref: callee
    loc: "./validate_add_lamports_comp.yaml"
    solana:
      progid: CZ6TBSh3boi6aPrgzjFGHumEHEewSWSqpziFaYtoz5tL
... 
methods:
  - name: add_lamports_to_pda
    solana:
      signers:
        - name: fee_payer
        - name: sender
    inputs:
      - name: sender
        type: sol:account_info
        solana:
          attributes: [ mut ]
      - name: recipient
        type: callee.PDA
        solana:
          attributes: [ mut ]
  - name: add_lamports_to_non_pda_whilst_initializing
    uses:
      - callee.init_non_pda
    solana:
      signers:
        - name: fee_payer
        - name: sender
    inputs:
      - name: sender
        type: sol:account_info
        solana:
          attributes: [ mut ]
...
```

While the imported cidl named `callee` in the ref is defined as:
```
cidl: "0.8"
info:
  name: validate_add_lamports_comp
...
```
This produces:
* at `Cargo.toml `of the Caller:
```
[dependencies]
anchor-lang = "0.28.0"
callee = { path = "../generated_callee", features = ["cpi"] } --------> This should be generated with the name of the imported cidl
```

* at `Cargo.toml` of the Callee:
```
[package]
name = "callee" --------> This should be generated with the name of the imported cidl
version = "0.0.0"
description = "This CIDL is use to support the test of validate_add_lamports.yaml"
edition = "2021"
```
* at `lib.rs `of the Callee
```
...
#[program]
pub mod callee { -------> This should be generated with the name of the imported cidl
    use super::*;
...
```

**Expected behavior**
To use the CIDL's defined <program name> of the imported program to generate its namespace, and apply wherever it is necessary.

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
