### ISSUE TITLE
Client signatures expects Pubkey|Keypair for signer accounts

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#55]
**Describe the bug**
The generated program client "sendAndConfirm" signatures expect a Union Type defined as `(Publickey | Keypair)` for params that later are used to sign the tx. Therefore, a TS error is not raised when passing a Pubkey as arg, but the tx will fail with "signature verification failed", since the private key was not provided.

**To Reproduce**
```
- name: add_lamports_direct_mode
    solana:
      signers:
        - name: fee_payer
        - name: sender
    inputs:
      - name: sender
        type: sol:account_info
        solana:
          attributes: [ mut ]
```
![image](https://github.com/Codigo-io/issues/assets/63513231/7783ca39-f310-427f-a279-a359547e02d1)

**Expected behavior**
To produce a signature with type `PublicKey` when the signature is not required, and `Keypair` when it does.

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
