### ISSUE TITLE
A PDA is required as Tx Signer

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#57]
**Describe the bug**
In the generated code from a CIDL that makes a cpi to a method that inits a PDA, the PDA is required as signer of the TX. This is not possible since PDAs don't have private keys.

**To Reproduce**
```
- name: add_lamports_to_pda_whilst_initializing
    uses:
      - callee.init_pda 
    solana:
      signers:
        - name: fee_payer
        - name: sender
    inputs:
      - name: sender
        type: sol:account_info
        solana:
          attributes: [ mut ]
```
Callee method CIDL:
```
methods:
  - name: init_pda
    inputs:
      - name: recipient
        type: PDA
        solana:
          attributes: [ init_if_needed ]
```

Generated Ix Context in lib.rs:
![image](https://github.com/Codigo-io/issues/assets/63513231/921c738e-dd09-4dbe-b710-9fe86da05588)

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
