### ISSUE TITLE
Seeds missing from pda client's Derive fn

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#58]
**Describe the bug**
In the Anchor client, the index seed is missing in the internal call to derive<AccountName>.

**To Reproduce**
```
...
types:
  Record:
      seeds:
        - name: record
        - name: signer
          type: sol:pubkey
        - name: index
          type: u8
...
```

Anchor client:
![image](https://github.com/Codigo-io/issues/assets/63513231/d116e6f3-8ee5-41a6-87b9-83bdce47aafa)
Notice how the index seed is missing in the call, although not in the Seeds object definition, which is correctly generated as

![image](https://github.com/Codigo-io/issues/assets/63513231/8f359295-fb7f-47a6-a8f6-587552398b4c)

**Expected behavior**
To produce a well crafted call.

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
