### ISSUE TITLE
Anchor client fn arg types wrongly generated

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#59]
**Describe the bug**
There are several types for which, when used as Ix params, the types on the correspondant client fns are generated as Publickeys:

* u128
* i128
* any supported option type
* any supported vector type

**To Reproduce**
```
- name: instruction1
    summary: Test MasterTypeNonPDA types
    inputs:
      - name: account
        type: MasterTypesNonPDA
        solana:
          attributes: [ init ]
      - name: u8_type
        type: u8
      - name: u16_type
        type: u16
      - name: u32_type
        type: u32
      - name: u64_type
        type: u64
      - name: u128_type
        type: u128
      - name: i8_type
        type: i8
      - name: i16_type
        type: i16
      - name: i32_type
        type: i32
      - name: i64_type
        type: i64
      - name: i128_type
        type: i128
      - name: string_type
        type: string
      - name: bool_type
        type: bool
      - name: f32_type
        type: f32
      - name: f64_type
        type: f64
      - name: pubkey_type
        type: sol:pubkey
      - name: account_info_type
        type: sol:account_info
      - name: account_info_type_mut
        type: sol:account_info
        solana:
          attributes: [mut]
      - name: u8_type_option
        type: rs:option<u8>
      - name: u16_type_option
        type: rs:option<u16>
      - name: u32_type_option
        type: rs:option<u32>
      - name: u64_type_option
        type: rs:option<u64>
      - name: u128_type_option
        type: rs:option<u128>
      - name: i8_type_option
        type: rs:option<i8>
      - name: i16_type_option
        type: rs:option<i16>
      - name: i32_type_option
        type: rs:option<i32>
      - name: i64_type_option
        type: rs:option<i64>
      - name: i128_type_option
        type: rs:option<i128>
      - name: string_type_option
        type: rs:option<string>
      - name: bool_type_option
        type: rs:option<bool>
      - name: f32_type_option
        type: rs:option<f32>
      - name: f64_type_option
        type: rs:option<f64>
      - name: pubkey_type_option
        type: rs:option<sol:pubkey>
      - name: u8_type_vector
        type: rs:vec<u8>
      - name: u16_type_vector
        type: rs:vec<u16>
      - name: u32_type_vector
        type: rs:vec<u32>
      - name: u64_type_vector
        type: rs:vec<u64>
      - name: u128_type_vector
        type: rs:vec<u128>
      - name: i8_type_vector
        type: rs:vec<i8>
      - name: i16_type_vector
        type: rs:vec<i16>
      - name: i32_type_vector
        type: rs:vec<i32>
      - name: i64_type_vector
        type: rs:vec<i64>
      - name: i128_type_vector
        type: rs:vec<i128>
      - name: bool_type_vector
        type: rs:vec<bool>
      - name: f32_type_vector
        type: rs:vec<f32>
      - name: f64_type_vector
        type: rs:vec<f64>
      - name: pubkey_type_vector
```

Generated client:

![image](https://github.com/Codigo-io/issues/assets/63513231/6a6a0c0e-9bda-48ec-b338-441f2654e955)

![image](https://github.com/Codigo-io/issues/assets/63513231/f0cb09e6-8b6c-4187-807d-2f0683f30268)

**Expected behavior**
To produce the expected type as defined.

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
