### ISSUE TITLE
Mapping a Seed to a Input generates multiple times the same seed as deriveFn args

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#62]
**Describe the bug**
As stated in the title, mapping a seed to a input generates multiple times the same seed as fetchFn args.

**To Reproduce**
```
- name: crazy_seeds_
    solana:
      signers:
        - name: fee_payer
        - name: signer_1
    inputs:
      - name: account
        type: PDAAccountVerifiesSeedsTypes
        solana:
          seeds:
            pubkey_type: signer_1
            u8_type: u8_type
            u16_type: u16_type
            u32_type: u32_type
            i8_type: i8_type
            i16_type: i16_type
            i32_type: i32_type
            string_type: string_type
      - name: u8_type
        type: u8
      - name: u16_type
        type: u16
      - name: u32_type
        type: u32
      - name: i8_type
        type: i8
      - name: i16_type
        type: i16
      - name: i32_type
        type: i32
      - name: string_type
        type: string
```

Generated client code:
![image](https://github.com/Codigo-io/issues/assets/63513231/3f5379ff-549d-4012-b8ca-704c4cc94023)

**Expected behavior**
To generate no extra crazy seeds as args.

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
