### ISSUE TITLE
Misleading account name for token_program account at processor

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#7]
**Describe the bug**
When trying to create a simple Mint, the token program account var name generated is ` csl_spl_token_v_0_0_0_info`, which is not clear.

**To Reproduce**
```
methods:
  - name: create_mint
    uses:
      - csl_spl_token.initialize_mint2
    inputs:
      - name: mint
        type: csl_spl_token.Mint
        solana:
          attributes: [ init ]
```

processor:

```
let account_info_iter = &mut accounts.iter();
let fee_payer_info = next_account_info(account_info_iter)?;
let mint_info = next_account_info(account_info_iter)?;
let system_program_info = next_account_info(account_info_iter)?;
**let csl_spl_token_v_0_0_0_info = next_account_info(account_info_iter)?;**
```
**Expected behavior**
To name the var `token_program_account_info`

**Código CLI version:**
 - Version v0.8
