### ISSUE TITLE
PDA address redundantly requested in client signature

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#78]
**Describe the bug**
Although dynamic seeds are params of a method client signature, the resultant PDA Address is also requested. This is redundant because knowing the seeds it is possible to derive the address in the client.

**To Reproduce**
```
- name: instruction8
  signers
    solana:
      signers:
        - name: fee_payer
        - name: signer_1
        - name: signer_2
        - name: signer_3
    inputs:
      - name: account
        type: PDAAccountVerifiesSeedsTypes
```

Generated client fn:
![image](https://github.com/Codigo-io/platform/assets/63513231/edf0fefc-453a-4ad1-9902-6d102975a81f)

**Expected behavior**
To not include the derived PDA address as fn param, and derive it inside the client, both in Ix builder & IxSendAndConfirm.

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
