### ISSUE TITLE
An external PDA with linked seeds generates a wrong client signature

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#79]
**Describe the bug**
When making a cpi to a method with a PDA with linked seeds, the generated client signature incorrectly uses not-linked seed names.

**To Reproduce**
```
- name: instruction53
  summary: Reference `validate_advanced_cases.instruction33`, where caller doesn't have inputs
  uses: [ validate_advanced_cases.instruction33 ]
```
validate_advanced_cases.instruction33:
```
- name: instruction33
  summary: Test `non-mut` with PDA account that maps seeds with signers and inputs
  solana:
    signers:
      - name: fee_payer
      - name: signer_1
      - name: signer_2
      - name: signer_3
  inputs:
    - name: account
      type: PDAAccountVerifiesSeedsTypes
      solana:
        seeds:
          pubkey_type: signer_1
          u8_type: u8_type
          u16_type: u16_type
          u32_type: u32_type
          i8_type: i8_type
          i16_type: i16_type
          i32_type: i32_type
          string_type: string_type
      - name: u8_type
        type: u8
      - name: u16_type
        type: u16
      - name: u32_type
        type: u32
      - name: i8_type
        type: i8
      - name: i16_type
        type: i16
      - name: i32_type
        type: i32
      - name: string_type
        type: string
```
Generated client:
![image](https://github.com/Codigo-io/platform/assets/63513231/9c31ce2b-7832-4d7d-8410-22d911270094)

**Expected behavior**
To use the seed var name as args.

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
