### ISSUE TITLE
using csl_spl_assoc_token namespace crashes the generator in Anchor

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#80]
**Describe the bug**
using csl_spl_assoc_token namespace crashes the generator in Anchor with 
`"error":"template: entrypoint_method_template:63:35: executing \"entrypoint_method_template\" at <GetMethodsInput $cpi_method $cpi_idl nil>: error calling GetMethodsInput: failed to get type from the reference"`

This doesn't happen in Native.

**To Reproduce**
```
- name: test_create
    uses:
      - csl_spl_assoc_token.create
    inputs:
      ...
```

**Expected behavior**
To generate valid code for the Anchor target.

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
