### ISSUE TITLE
Not recognized type in Anchor

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#81]
**Describe the bug**
Using `rs:c_option<sol:pubkey>` as type generates an invalid rust type in Anchor.

**To Reproduce**
```
...
Mint:
    solana:
      owner: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
    fields:
      - name: mint_authority
        type: rs:c_option<sol:pubkey>
...
```

Generates in lib.rs:
```
pub fn cpi_csl_spl_token_initialize_mint2(
    &self,
    decimals:u8, 
    mint_authority:Pubkey, 
    freeze_authority:rs:c_option<sol:pubkey> --> INVALID
) -> Result<()> {
... 
```

**Expected behavior**
To generate `Option<Pubkey>` in Anchor, the expected type in anchor-spl wrappers.

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
   
**Additional context**
The kw used `rs:c_option` suggests that COption is a rust's native type, but it is a custom type defined by the solana_program crate. I think it should be fixed too.
