### ISSUE TITLE
`payer` attr not generated for `init` of spl accounts

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#82]
**Describe the bug**
When generating code for a ix that use a spl account marked as init, the generated code doesn't include the mandatory `payer` attribute.

**To Reproduce**
```
 - name: mint
    uses:
      - csl_spl_token.initialize_mint2
      - csl_spl_assoc_token.create
      - csl_spl_token.mint_to
      - csl_spl_token.set_authority
    inputs:
      - name: mint
        type: csl_spl_token.Mint
        solana:
          attributes: [ init ]
...
```

Generated code:
![image](https://github.com/Codigo-io/platform/assets/63513231/662feede-a17c-4da0-91d7-53cee95455ac)

**Expected behavior**
To use the feePayer  as rent-payer if not specified, or the designed rent-payer if present.

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
   
**Additional context**
