### ISSUE TITLE
`uses` inputs overrides user defined ones

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#89]
**Describe the bug**
Not sure if this is a bug or not, but if inputs ixs defined in the `uses` field have inputs with the same name as user defined ones, the clash is resolved in favor of the `uses` ix. This prevented me from implementing a workaround for the current state of development to generate a CIDL with tokenProgram's accounts initialization.

**To Reproduce**
```
ethods:
  - name: mint
    uses:
      - csl_spl_token.initialize_mint2
    inputs:
      - name: mint
        type: sol:account_info
```

generated code (unbuildeable):
```
#[account(signer, init)]
pub mint: Account<'info, anchor_spl::token::Mint>,
```

**Expected behavior**
To prioritize user defined inputs over `uses` related inputs.

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
