### ISSUE TITLE
Generate a CIDL with +1 method with the same name is possible

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#92]
**Describe the bug**
Generating a CIDL that has two or more method with the same name it is possible, but not buildeable.

**To Reproduce**
```
 # using default's `fee_payer` as fee payer and rent payer
  - name: create_pet_if_needed
    inputs:
      - name: pet
        type: Pet
        solana:
          attributes: [ init_if_needed ]
      - name: neim
        type: string

  # using defined rent payer
  - name: create_pet_if_needed
    solana:
      signers:
          - name: fee_payer
          - name: owner_2
    inputs:
      - name: pet
        type: Pet
        solana:
          attributes: [ init_if_needed ]
          seeds:
            owner: owner_2
      - name: neim
        type: string
```
Generated code:
Anchor:
`pub fn create_pet_if_needed(ctx: Context<CreatePetIfNeeded>,neim:String, pet_seed_owner:Pubkey) -> Result<()> {...`
`pub fn create_pet_if_needed(ctx: Context<CreatePetIfNeeded>,neim:String) -> Result<()> {...`

Error:
![image](https://github.com/Codigo-io/platform/assets/63513231/35eaf25c-b3b4-4d26-add6-d13d76f71747)

Native:
```
pub fn process_create_pet_if_needed(
		program_id: &Pubkey,
		accounts: &[AccountInfo],
		neim: String,
		pet_seed_owner: Pubkey,
	) -> ProgramResult {
...
pub fn process_create_pet_if_needed(
		program_id: &Pubkey,
		accounts: &[AccountInfo],
		neim: String,
	) -> ProgramResult {
```

Error:
![image](https://github.com/Codigo-io/platform/assets/63513231/330dd0eb-a0a2-4689-83d3-3d346c68104b)

**Expected behavior**
To throw an error with a hint

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]
